[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
serviceName = "sec-sumariser"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"

[services.healthcheck]
path = "/"
intervalSeconds = 30
timeoutSeconds = 10